---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: cont-1
        image: shaikmustafa/dm
        ports:
        - containerPort: 80
  ---
  apiVersion: v1
kind: Service
metadata:
  name: devops
spec:
  type: NodePort
  selector:
    app: my-app
  ports:
  - port: 80          
    targetPort: 80     
    nodePort: 30007   

